### ISSUE TITLE
onTabState called with only selected position

### ISSUE THREAD

**Issue by BSnaxx** [81813780/HandyTabBar#1]
In my implementation, I see onTabState called 4 times, for my 4 tabs, except that the position argument is the same for all 4. If you look around line 227 of HandyTabBar.java:

```
private void setActiveTab(int position) {
    for (int i = 0; i < tabCount; i++) {
        View v = mTabsContainer.getChildAt(i);
        boolean isSelected=false;
        if (position==i){
            isSelected=true;
        }
        mTabLayout.onTabState(v,isSelected,position);
    }
}
```

Shouldn't it be:             mTabLayout.onTabState(v,isSelected,i);

**Comment by 81813780** [comment]
you are right ,onTabState should't called 4 times , I will solve this soon, And Welcome BSnaxx . Submit a Pull Request If you are done editing the code

**Comment by HarlonWang** [comment]
As my understand ,I checked my code,in my case I called onTabState many times when one tabs selected,the others tabs should be set normal status ,so in onTabState method ,I write sample code like this, 

``` java
    @Override
    public void onTabState(View v, boolean isSelected,int position) {
        ImageView imageView= (ImageView) v.findViewById(R.id.yourViewID);
        if (isSelected){
             // should be set selected status 
             ...
        }else {
            // should be set normal status 
            ...
        }
    }
```

recently this is my solution,If I have better implementation, I will instead of this,of Course If you have better,welcome send PR,and thanks again.
